version: "3"
services:
  traefik:
    image: traefik:v2.2
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"                       # Traefik will listen on port 8080 by default for API request
      - "--providers.docker=true"                   # Enabling docker provider
      - "--providers.docker.exposedbydefault=false" # Do not expose containers unless explicitly told so
      - "--entrypoints.web.address=:80"             # Traefik will listen to incoming request on the port 80 (HTTP)
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # So that Traefik can listen to the Docker events

  security:
    image: go-docker-image
    environment:
      - DB_PORT=5432
      - DB_HOST=docker.for.mac.host.internal
    ports:
      - '6000:6000'
    volumes:
      - ./security/.:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.security.rule=Host(`localhost`) && PathPrefix(`/security`)"
      - "traefik.http.routers.security.middlewares=security-stripprefix"
      - "traefik.http.middlewares.security-stripprefix.stripprefix.prefixes=/security"
      - "traefik.http.routers.security.entrypoints=web"
