version: "3"
services:
  security:
    image: go-docker-image
    environment:
      - DB_PORT=5432
      - DB_HOST=docker.for.mac.host.internal
    ports:
      - '6000:6000'
    volumes:
      - ./security/.:/app